/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andig' at '11/14/16 7:08 PM' with Gradle 3.1
 *
 * @author andig, @date 11/14/16 7:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
